package com.conformiq.conformiq_automation3x.utilities;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utility class for logging test execution.
 * Generated by Conformiq Cloud
 */
public class TestLogger {
    private static final Logger logger = LoggerFactory.getLogger(TestLogger.class);

    /**
     * Logs the start of a test
     * 
     * @param testName Name of the test
     * @param testId   ID of the test
     */
    public static void logTestStart(String testName, String testId) {
        logger.info("========================================");
        logger.info("Starting test: {} (ID: {})", testName, testId);
        logger.info("========================================");
    }

    /**
     * Logs the end of a test
     * 
     * @param testName Name of the test
     * @param testId   ID of the test
     */
    public static void logTestEnd(String testName, String testId) {
        logger.info("========================================");
        logger.info("Completed test: {} (ID: {})", testName, testId);
        logger.info("========================================");
    }

    /**
     * Logs a test step
     * 
     * @param stepDescription Description of the step
     */
    public static void logStep(String stepDescription) {
        logger.info("Step: {}", stepDescription);
    }

    /**
     * Logs test data
     * 
     * @param key   Data key
     * @param value Data value
     */
    public static void logData(String key, String value) {
        logger.info("Data: {} = {}", key, value);
    }

    /**
     * Logs an assertion
     * 
     * @param assertion Assertion description
     */
    public static void logAssertion(String assertion) {
        logger.info("Assertion: {}", assertion);
    }
}
